/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AbSlider {
    /**
    * The last name
    */
    'last': string;
  }
}

declare global {


  interface HTMLAbSliderElement extends Components.AbSlider, HTMLStencilElement {}
  var HTMLAbSliderElement: {
    prototype: HTMLAbSliderElement;
    new (): HTMLAbSliderElement;
  };
  interface HTMLElementTagNameMap {
    'ab-slider': HTMLAbSliderElement;
  }
}

declare namespace LocalJSX {
  interface AbSlider extends JSXBase.HTMLAttributes<HTMLAbSliderElement> {
    /**
    * The last name
    */
    'last'?: string;
  }

  interface IntrinsicElements {
    'ab-slider': AbSlider;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


