/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AbColors {}
  interface AbLayoutSection {
    'header': string;
    'subHeader': string;
  }
  interface AbNativeSlider {
    'max': number;
    'min': number;
    'name': string;
    'step': number;
    'value': number;
  }
  interface AbRating {
    'maxValue': number;
    'value': number;
  }
  interface AbToogleButton {}
  interface AbToogleGroup {}
}

declare global {


  interface HTMLAbColorsElement extends Components.AbColors, HTMLStencilElement {}
  var HTMLAbColorsElement: {
    prototype: HTMLAbColorsElement;
    new (): HTMLAbColorsElement;
  };

  interface HTMLAbLayoutSectionElement extends Components.AbLayoutSection, HTMLStencilElement {}
  var HTMLAbLayoutSectionElement: {
    prototype: HTMLAbLayoutSectionElement;
    new (): HTMLAbLayoutSectionElement;
  };

  interface HTMLAbNativeSliderElement extends Components.AbNativeSlider, HTMLStencilElement {}
  var HTMLAbNativeSliderElement: {
    prototype: HTMLAbNativeSliderElement;
    new (): HTMLAbNativeSliderElement;
  };

  interface HTMLAbRatingElement extends Components.AbRating, HTMLStencilElement {}
  var HTMLAbRatingElement: {
    prototype: HTMLAbRatingElement;
    new (): HTMLAbRatingElement;
  };

  interface HTMLAbToogleButtonElement extends Components.AbToogleButton, HTMLStencilElement {}
  var HTMLAbToogleButtonElement: {
    prototype: HTMLAbToogleButtonElement;
    new (): HTMLAbToogleButtonElement;
  };

  interface HTMLAbToogleGroupElement extends Components.AbToogleGroup, HTMLStencilElement {}
  var HTMLAbToogleGroupElement: {
    prototype: HTMLAbToogleGroupElement;
    new (): HTMLAbToogleGroupElement;
  };
  interface HTMLElementTagNameMap {
    'ab-colors': HTMLAbColorsElement;
    'ab-layout-section': HTMLAbLayoutSectionElement;
    'ab-native-slider': HTMLAbNativeSliderElement;
    'ab-rating': HTMLAbRatingElement;
    'ab-toogle-button': HTMLAbToogleButtonElement;
    'ab-toogle-group': HTMLAbToogleGroupElement;
  }
}

declare namespace LocalJSX {
  interface AbColors extends JSXBase.HTMLAttributes<HTMLAbColorsElement> {}
  interface AbLayoutSection extends JSXBase.HTMLAttributes<HTMLAbLayoutSectionElement> {
    'header'?: string;
    'subHeader'?: string;
  }
  interface AbNativeSlider extends JSXBase.HTMLAttributes<HTMLAbNativeSliderElement> {
    'max'?: number;
    'min'?: number;
    'name'?: string;
    'step'?: number;
    'value'?: number;
  }
  interface AbRating extends JSXBase.HTMLAttributes<HTMLAbRatingElement> {
    'maxValue'?: number;
    'value'?: number;
  }
  interface AbToogleButton extends JSXBase.HTMLAttributes<HTMLAbToogleButtonElement> {}
  interface AbToogleGroup extends JSXBase.HTMLAttributes<HTMLAbToogleGroupElement> {}

  interface IntrinsicElements {
    'ab-colors': AbColors;
    'ab-layout-section': AbLayoutSection;
    'ab-native-slider': AbNativeSlider;
    'ab-rating': AbRating;
    'ab-toogle-button': AbToogleButton;
    'ab-toogle-group': AbToogleGroup;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


