/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AbSlider {
    'max': number;
    'min': number;
    'name': string;
    'step': number;
    'value': number;
  }
}

declare global {


  interface HTMLAbSliderElement extends Components.AbSlider, HTMLStencilElement {}
  var HTMLAbSliderElement: {
    prototype: HTMLAbSliderElement;
    new (): HTMLAbSliderElement;
  };
  interface HTMLElementTagNameMap {
    'ab-slider': HTMLAbSliderElement;
  }
}

declare namespace LocalJSX {
  interface AbSlider extends JSXBase.HTMLAttributes<HTMLAbSliderElement> {
    'max'?: number;
    'min'?: number;
    'name'?: string;
    'step'?: number;
    'value'?: number;
  }

  interface IntrinsicElements {
    'ab-slider': AbSlider;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


